"""Email service — async email delivery via SMTP."""
import logging
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from uuid import UUID

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import get_settings
from app.models.base import User, Household

logger = logging.getLogger(__name__)
settings = get_settings()


class EmailService:
    """Send email notifications."""

    def __init__(self, db: AsyncSession):
        self.db = db

    async def _get_household_email(self, household_id: UUID) -> str | None:
        """Get the primary user's email-like identifier for a household."""
        result = await self.db.execute(
            select(User)
            .join(Household, Household.primary_user_id == User.id)
            .where(Household.id == str(household_id))
        )
        result.scalar_one_or_none()
        # In this app, username is used as identifier. For email,
        # you'd need an email field on the User model.
        return None  # Placeholder — add email field to User model when needed

    async def send(self, to: str, subject: str, html_body: str) -> bool:
        """Send an email. Returns True on success."""
        if not settings.EMAIL_ENABLED or not settings.SMTP_HOST:
            logger.debug("Email disabled or SMTP not configured")
            return False

        try:
            import aiosmtplib

            msg = MIMEMultipart("alternative")
            msg["From"] = settings.SMTP_FROM
            msg["To"] = to
            msg["Subject"] = subject
            msg.attach(MIMEText(html_body, "html"))

            await aiosmtplib.send(
                msg,
                hostname=settings.SMTP_HOST,
                port=settings.SMTP_PORT,
                username=settings.SMTP_USER or None,
                password=settings.SMTP_PASSWORD or None,
                use_tls=True,
            )
            logger.info("Email sent to %s: %s", to, subject)
            return True
        except Exception as exc:
            logger.warning("Failed to send email to %s: %s", to, exc)
            return False

    async def send_reminder_notification(
        self, to: str, member_name: str, reminder_title: str, due_date: str
    ) -> bool:
        """Send a reminder notification email."""
        html = f"""
        <div style="font-family: sans-serif; max-width: 480px; margin: 0 auto;">
            <h2 style="color: #1a2b42;">Health Reminder</h2>
            <p><strong>{member_name}</strong> has a reminder due:</p>
            <div style="background: #f5f5f5; border-radius: 8px; padding: 16px; margin: 16px 0;">
                <p style="margin: 0; font-size: 16px;"><strong>{reminder_title}</strong></p>
                <p style="margin: 4px 0 0; color: #737373;">Due: {due_date}</p>
            </div>
            <p style="color: #737373; font-size: 12px;">
                This is an automated reminder from Health Keeper.
            </p>
        </div>
        """
        return await self.send(to, f"Reminder: {reminder_title}", html)

    async def send_alert_notification(
        self, to: str, member_name: str, alert_title: str, severity: str
    ) -> bool:
        """Send a health alert notification email."""
        color = "#dc2626" if severity == "critical" else "#d97706" if severity == "warning" else "#2563eb"
        html = f"""
        <div style="font-family: sans-serif; max-width: 480px; margin: 0 auto;">
            <h2 style="color: {color};">Health Alert: {severity.title()}</h2>
            <p><strong>{member_name}</strong> — {alert_title}</p>
            <p style="color: #737373; font-size: 12px;">
                This alert was generated by Health Keeper's health monitoring system.
                Please consult a healthcare professional for medical advice.
            </p>
        </div>
        """
        return await self.send(to, f"Health Alert: {alert_title}", html)
