"""add health alerts indexes and fix audit json type

Revision ID: 2fd22ac8db51
Revises: 6ea4e1d79d20
Create Date: 2026-04-24 19:24:04.301461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fd22ac8db51'
down_revision: Union[str, Sequence[str], None] = '6ea4e1d79d20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('revoked_tokens')
    op.alter_column('ai_insights', 'verification_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'"))
    op.alter_column('ai_insights', 'verification_claims_checked',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('ix_ai_insights_conversation_id'), 'ai_insights', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_ai_insights_health_record_id'), 'ai_insights', ['health_record_id'], unique=False)
    op.create_index(op.f('ix_attachments_health_record_id'), 'attachments', ['health_record_id'], unique=False)
    op.alter_column('family_members', 'relationship_type',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('SELF', 'WIFE', 'SON', 'DAUGHTER', 'GRAND_SON', 'GRAND_DAUGHTER', 'DAUGHTER_IN_LAW', 'SON_IN_LAW', 'OTHERS', name='relationship'),
               existing_nullable=False)
    op.create_index(op.f('ix_family_members_is_active'), 'family_members', ['is_active'], unique=False)
    op.create_index('ix_health_alerts_household_dismissed', 'health_alerts', ['household_id', 'is_dismissed'], unique=False)
    op.create_index('ix_health_alerts_member_dismissed', 'health_alerts', ['family_member_id', 'is_dismissed'], unique=False)
    op.create_index('ix_health_records_member_deleted_date', 'health_records', ['family_member_id', 'is_deleted', 'record_date'], unique=False)
    op.create_index('ix_health_records_member_type_deleted_date', 'health_records', ['family_member_id', 'record_type', 'is_deleted', 'record_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_health_records_member_type_deleted_date', table_name='health_records')
    op.drop_index('ix_health_records_member_deleted_date', table_name='health_records')
    op.drop_index('ix_health_alerts_member_dismissed', table_name='health_alerts')
    op.drop_index('ix_health_alerts_household_dismissed', table_name='health_alerts')
    op.drop_index(op.f('ix_family_members_is_active'), table_name='family_members')
    op.alter_column('family_members', 'relationship_type',
               existing_type=sa.Enum('SELF', 'WIFE', 'SON', 'DAUGHTER', 'GRAND_SON', 'GRAND_DAUGHTER', 'DAUGHTER_IN_LAW', 'SON_IN_LAW', 'OTHERS', name='relationship'),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)
    op.drop_index(op.f('ix_attachments_health_record_id'), table_name='attachments')
    op.drop_index(op.f('ix_ai_insights_health_record_id'), table_name='ai_insights')
    op.drop_index(op.f('ix_ai_insights_conversation_id'), table_name='ai_insights')
    op.alter_column('ai_insights', 'verification_claims_checked',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('ai_insights', 'verification_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'"))
    op.create_table('revoked_tokens',
    sa.Column('jti', sa.VARCHAR(length=64), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('jti')
    )
    # ### end Alembic commands ###
