"""initial_schema

Revision ID: 6ea4e1d79d20
Revises: 
Create Date: 2026-04-12 23:12:08.311678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ea4e1d79d20'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('family_members', 'relationship_type',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('SELF', 'WIFE', 'SON', 'DAUGHTER', 'GRAND_SON', 'GRAND_DAUGHTER', 'DAUGHTER_IN_LAW', 'SON_IN_LAW', 'OTHERS', name='relationship'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('family_members', 'relationship_type',
               existing_type=sa.Enum('SELF', 'WIFE', 'SON', 'DAUGHTER', 'GRAND_SON', 'GRAND_DAUGHTER', 'DAUGHTER_IN_LAW', 'SON_IN_LAW', 'OTHERS', name='relationship'),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)
    # ### end Alembic commands ###
