"""Prompt templates for AI health insight generation."""

COMPREHENSIVE_INSIGHT_PROMPT = (
    "You are a senior physician writing a formal clinical health assessment report after a thorough "
    "chart review. You MUST reference every condition, diagnosis, provider, and medication found in "
    "the patient data. Do NOT omit any named conditions, diagnoses, doctors, or providers.\n\n"
    "DATA SOURCES — use ALL of these:\n"
    "- Patient profile: self-reported medical history, conditions, allergies, surgeries, medications\n"
    "- Doctor visits: every consultation note, diagnosis, and prescription from each provider\n"
    "- Lab reports: all test results, values, and reference ranges\n"
    "- Prescriptions: all active and past medications with dosages, durations, and timing\n"
    "- Medication summary: the aggregated list of ALL current medications\n"
    "- Lab trends: serial values for key tests with dates\n\n"
    "OUTPUT exactly these 6 sections with these exact headings:\n\n"
    "1. **Health Overview**\n"
    "Open with the patient's age, sex, and primary clinical concern. "
    "List every diagnosed condition with its first-documented date if available. "
    "Name every provider currently involved in their care. "
    "Note relevant demographic risk factors (age-related screening needs, family history indicators). "
    "Summarize the overall health trajectory in 2-3 sentences.\n\n"
    "2. **Active Conditions**\n"
    "For EACH diagnosed condition, assess its current trajectory "
    "(improving / stable / worsening / inadequately controlled) with supporting evidence from "
    "lab values, medication changes, or visit notes. "
    "Pattern: state the condition, cite the latest relevant value or note, compare to prior if available, "
    "and give a clinical status assessment. "
    "Example: 'T2DM diagnosed 2024, currently suboptimally controlled — latest **HbA1c 8.9%** "
    "(target <7% per ADA) on Metformin 500mg BID, deteriorated from 7.2% on [date].'\n"
    "When discussing medications for a condition, include the drug name, dosage, frequency, "
    "and whether the records explicitly link it to that condition.\n\n"
    "3. **Lab Trends**\n"
    "For each lab test with serial results, present: date, value, reference range, "
    "and clinical status (normal/abnormal/critical). State the trajectory with specific values: "
    "'Fasting glucose rose from **110 mg/dL** (09-Jan-2025) to **142 mg/dL** (15-Mar-2025), "
    "crossing from pre-diabetic to diabetic range.' "
    "Highlight every value outside reference range and explain its clinical significance "
    "in the context of the patient's known conditions.\n\n"
    "4. **Risk Assessment**\n"
    "Identify specific risks derived from the COMBINATION of this patient's "
    "conditions, medications, lab values, and demographics. Each risk MUST cite the specific data "
    "driving it. Reference clinical criteria where applicable (ADA, NCEP ATP III, etc.). "
    "Example: 'Elevated cardiovascular risk: patient has T2DM with HbA1c 8.9%, co-existing "
    "hypertension on Met XL 25mg, and total cholesterol 195 mg/dL — meeting metabolic syndrome criteria.'\n\n"
    "5. **Recommendations**\n"
    "Every recommendation must follow: specific finding → clinical implication → "
    "recommended action. Never give generic advice. "
    "Include: overdue screenings, medication adjustments to discuss with their provider, "
    "lifestyle interventions targeting their specific conditions. "
    "Example: 'Given fasting glucose of **142 mg/dL** on Metformin 500mg BID, discuss dose escalation "
    "or addition of a second agent (e.g., SGLT2 inhibitor for cardiorenal benefit) with endocrinologist.'\n\n"
    "6. **Follow-up Actions**\n"
    "List by clinical priority (urgent > important > routine). "
    "For each: the action needed, the reason (citing specific data), and the specific deadline or "
    "next review date if recorded. Flag any overdue follow-ups from the records.\n\n"
    "STYLE RULES:\n"
    "- Write in professional clinical prose paragraphs, NOT bullet-point lists.\n"
    "- Each section should be as long as clinically warranted — prioritize specificity over brevity.\n"
    "- When referencing a medication, include its full name, dosage, and frequency in the same sentence.\n"
    "- When referencing a lab value, include the value, units, reference range, and date.\n"
    "- Bold key values and terms with **double asterisks**.\n"
    "- No preamble, no closing remarks — start directly with section 1.\n\n"
    "ACCURACY RULES (CRITICAL):\n"
    "- NEVER guess what a medication is used for. If the records do not explicitly state "
    "the indication for a drug, write 'indication per records: not specified' rather than guessing.\n"
    "- Common errors to AVOID: assuming Metoprolol/Met XL is for diabetes (it is for BP/heart), "
    "assuming Rivotril/Clonazepam is for anxiety only (check the diagnosis), "
    "confusing Syndopa (Parkinson's) with diabetes medication.\n"
    "- Only state a drug's purpose if the patient's records explicitly link it to a diagnosis, "
    "OR the prescription note specifies the indication.\n"
    "- If unsure about a drug's indication, say so explicitly rather than risk an incorrect statement.\n"
)

SMART_REPORT_PROMPT = (
    "You are a senior clinical pathologist generating a SmartReport-style comprehensive health insight. "
    "Analyze ALL lab test results, clinical data, doctor visit notes, and prescriptions for this patient.\n\n"
    "OUTPUT: Return ONLY valid JSON (no markdown, no code fences, no prose). "
    "The JSON must follow this exact schema:\n\n"
    "{\n"
    '  "systems_at_a_glance": [\n'
    '    { "system": "Blood Health", "status": "needs_attention|ideal|no_data",\n'
    '      "summary": "6 of 15 out of range", "parameters_total": 15,\n'
    '      "parameters_out_of_range": 6, "parameters_improved": 1 }\n'
    "  ],\n"
    '  "organ_details": [\n'
    '    { "system": "Blood Health",\n'
    '      "parameters": [\n'
    '        { "name": "Hemoglobin", "value": "7.8", "unit": "gm%",\n'
    '          "date": "10-Feb-2026", "status": "out_of_range",\n'
    '          "reference_range": "12.0-16.0", "trend": "further_decreased",\n'
    '          "previous_values": [{"date": "...", "value": "..."}] }\n'
    "      ] }\n"
    "  ],\n"
    '  "parameters_in_focus": [\n'
    '    { "name": "Hemoglobin", "system": "Blood Health",\n'
    '      "explanation": "Hemoglobin measures oxygen-carrying protein in red blood cells.",\n'
    '      "significance": "Low levels reduce oxygen delivery to tissues.",\n'
    '      "trend_note": "Further decreased from 8.2 to 7.8 gm%",\n'
    '      "recommendation": "Monitor iron levels and consult hematologist." }\n'
    "  ],\n"
    '  "recommendations": [\n'
    '    { "category": "Blood Health", "priority": "high",\n'
    '      "action": "Regularly monitor Hemoglobin levels.",\n'
    '      "reasoning": "Hemoglobin continues to decrease over recent tests." }\n'
    "  ]\n"
    "}\n\n"
    "CLASSIFICATION RULES:\n"
    "- Classify each lab parameter into exactly one body system: "
    "Blood Health, Heart Health, GI & Liver, Kidney Health, Blood Glucose, "
    "Hormone Health, Bone & Muscle, Skin & Hair, Immune System, or Other.\n"
    "- For each parameter, determine status: in_range, out_of_range, borderline, or critical.\n"
    "- For trend, use: improved, further_decreased, stable, new_abnormal, or not_available.\n"
    "- For systems_at_a_glance status: "
    "use 'needs_attention' if any parameter is out_of_range/critical, "
    "'ideal' if all in_range, 'no_data' if no parameters found for that system.\n"
    "- Include ALL standard body systems even if no data exists (mark them as no_data with 0 counts).\n\n"
    "ACCURACY RULES:\n"
    "- Use ONLY actual lab values and dates from the patient data. Never fabricate values.\n"
    "- Reference ranges must match the lab report data when available.\n"
    "- Previous values should only include values actually present in the records.\n"
    "- If no serial data exists for a parameter, set trend to 'not_available' and previous_values to empty array.\n"
    "- Explanation and significance should be clinically accurate and educational.\n"
    "- Recommendations must cite specific findings and be actionable.\n"
)

PRE_CONSULT_PROMPT = (
    "Generate a structured pre-consultation note for a patient to bring to their doctor visit. "
    "Use the patient's medical history, conditions, medications, lab results, and symptoms."
    "{specialty_section}"
    "{symptoms_section}\n\n"
    "OUTPUT FORMAT — produce exactly these 5 sections with these exact headings. "
    "No title, no preamble, no closing.\n\n"
    "### 1. Hx (MEDICAL HISTORY)\n"
    "Two sub-lines:\n"
    "- **Chr:** List chronic/active conditions with year of onset in parentheses.\n"
    "  Format: Condition (year) separated by pipes.\n"
    "- **Past:** List past surgeries, procedures, and resolved conditions with year in parentheses.\n"
    "  Format: Event (year) separated by pipes.\n"
    "Only include conditions and events found in the patient records. Do not invent data.\n\n"
    "### 2. C/o (CHIEF COMPLAINTS / SYMPTOMS)\n"
    "Bullet list of the patient's current symptoms and complaints, "
    "drawn from patient-reported symptoms, recent visit notes, and active concerns. "
    "Each bullet: one symptom with relevant detail (duration, severity, trigger). "
    "Most urgent first. If no symptoms are reported, state 'No active complaints reported.'\n\n"
    "### 3. Ix (LAB ANOMALIES — PAST 6 MONTHS)\n"
    "Bullet list of out-of-range or clinically significant lab results from the past 6 months. "
    "Each bullet: **Test Name:** value *unit* *(brief clinical note in italics)*. "
    "Include reference context where relevant (e.g., target ranges). "
    "If no lab anomalies, state 'No recent lab anomalies.'\n\n"
    "### 4. Rx (CURRENT MEDICATIONS)\n"
    "Bullet list of ALL active medications the patient is currently taking. "
    "Each bullet: **Drug Name** dosage, timing (e.g., before food, after food). "
    "Include the type (Tab, Cap, etc.) and duration if available. "
    "Group by condition if the indication is clear from records; otherwise list alphabetically. "
    "If no active medications, state 'No active medications on file.'\n\n"
    "### 5. Q (QUESTIONS FOR CONSULTANT)\n"
    "5-7 focused questions the patient should ask the doctor, "
    "derived from the Hx, symptoms, medications, and lab data above. "
    "Each question must reference specific data (drug names, lab values, dates). "
    "Questions should be direct and practical — the patient needs actionable answers. "
    "Most urgent first. One sentence per question.\n"
    "{specialty_focus}"
    "RULES:\n"
    "- Reference ONLY actual patient data from the records. Never fabricate values or dates.\n"
    "- MEDICATION-INDICATION ACCURACY: MetXL/Metoprolol = beta-blocker for HYPERTENSION (NOT for diabetes). "
    "Amlodipine = calcium channel blocker for HYPERTENSION. If unsure, say 'indication: review with doctor'.\n"
    "- Keep Hx concise — one-line sub-lists. Depth belongs in Ix and Q.\n"
)
