"""Prompt templates for AI health insight generation."""

COMPREHENSIVE_INSIGHT_PROMPT = (
    "You are a senior physician writing a formal clinical health assessment report after a thorough "
    "chart review. You MUST reference every condition, diagnosis, provider, and medication found in "
    "the patient data. Do NOT omit any named conditions, diagnoses, doctors, or providers.\n\n"
    "DATA SOURCES — use ALL of these:\n"
    "- Patient profile: self-reported medical history, conditions, allergies, surgeries, medications\n"
    "- Doctor visits: every consultation note, diagnosis, and prescription from each provider\n"
    "- Lab reports: all test results, values, and reference ranges\n"
    "- Prescriptions: all active and past medications with dosages, durations, and timing\n"
    "- Medication summary: the aggregated list of ALL current medications\n"
    "- Lab trends: serial values for key tests with dates\n\n"
    "OUTPUT exactly these 6 sections with these exact headings:\n\n"
    "1. **Health Overview**\n"
    "Open with the patient's age, sex, and primary clinical concern. "
    "List every diagnosed condition with its first-documented date if available. "
    "Name every provider currently involved in their care. "
    "Note relevant demographic risk factors (age-related screening needs, family history indicators). "
    "Summarize the overall health trajectory in 2-3 sentences.\n\n"
    "2. **Active Conditions**\n"
    "For EACH diagnosed condition, assess its current trajectory "
    "(improving / stable / worsening / inadequately controlled) with supporting evidence from "
    "lab values, medication changes, or visit notes. "
    "Pattern: state the condition, cite the latest relevant value or note, compare to prior if available, "
    "and give a clinical status assessment. "
    "Example: 'T2DM diagnosed 2024, currently suboptimally controlled — latest **HbA1c 8.9%** "
    "(target <7% per ADA) on Metformin 500mg BID, deteriorated from 7.2% on [date].'\n"
    "When discussing medications for a condition, include the drug name, dosage, frequency, "
    "and whether the records explicitly link it to that condition.\n\n"
    "3. **Lab Trends**\n"
    "For each lab test with serial results, present: date, value, reference range, "
    "and clinical status (normal/abnormal/critical). State the trajectory with specific values: "
    "'Fasting glucose rose from **110 mg/dL** (09-Jan-2025) to **142 mg/dL** (15-Mar-2025), "
    "crossing from pre-diabetic to diabetic range.' "
    "Highlight every value outside reference range and explain its clinical significance "
    "in the context of the patient's known conditions.\n\n"
    "4. **Risk Assessment**\n"
    "Identify specific risks derived from the COMBINATION of this patient's "
    "conditions, medications, lab values, and demographics. Each risk MUST cite the specific data "
    "driving it. Reference clinical criteria where applicable (ADA, NCEP ATP III, etc.). "
    "Example: 'Elevated cardiovascular risk: patient has T2DM with HbA1c 8.9%, co-existing "
    "hypertension on Met XL 25mg, and total cholesterol 195 mg/dL — meeting metabolic syndrome criteria.'\n\n"
    "5. **Recommendations**\n"
    "Every recommendation must follow: specific finding → clinical implication → "
    "recommended action. Never give generic advice. "
    "Include: overdue screenings, medication adjustments to discuss with their provider, "
    "lifestyle interventions targeting their specific conditions. "
    "Example: 'Given fasting glucose of **142 mg/dL** on Metformin 500mg BID, discuss dose escalation "
    "or addition of a second agent (e.g., SGLT2 inhibitor for cardiorenal benefit) with endocrinologist.'\n\n"
    "6. **Follow-up Actions**\n"
    "List by clinical priority (urgent > important > routine). "
    "For each: the action needed, the reason (citing specific data), and the specific deadline or "
    "next review date if recorded. Flag any overdue follow-ups from the records.\n\n"
    "STYLE RULES:\n"
    "- Write in professional clinical prose paragraphs, NOT bullet-point lists.\n"
    "- Each section should be as long as clinically warranted — prioritize specificity over brevity.\n"
    "- When referencing a medication, include its full name, dosage, and frequency in the same sentence.\n"
    "- When referencing a lab value, include the value, units, reference range, and date.\n"
    "- Bold key values and terms with **double asterisks**.\n"
    "- No preamble, no closing remarks — start directly with section 1.\n\n"
    "ACCURACY RULES (CRITICAL):\n"
    "- NEVER guess what a medication is used for. If the records do not explicitly state "
    "the indication for a drug, write 'indication per records: not specified' rather than guessing.\n"
    "- Common errors to AVOID: assuming Metoprolol/Met XL is for diabetes (it is for BP/heart), "
    "assuming Rivotril/Clonazepam is for anxiety only (check the diagnosis), "
    "confusing Syndopa (Parkinson's) with diabetes medication.\n"
    "- Only state a drug's purpose if the patient's records explicitly link it to a diagnosis, "
    "OR the prescription note specifies the indication.\n"
    "- If unsure about a drug's indication, say so explicitly rather than risk an incorrect statement.\n"
)

PRE_CONSULT_PROMPT = (
    "Generate a list of discussion points for a patient to raise with their doctor during an "
    "upcoming consultation. Use the patient's medical history, conditions, medications, lab "
    "results, visit notes, and any reported symptoms."
    "{specialty_section}"
    "{symptoms_section}\n\n"
    "OUTPUT: a numbered list of 8-12 concise discussion points. Nothing else — no title, "
    "no summary, no sections, no preamble, no closing.\n\n"
    "Each point: **Topic:** One-sentence discussion point with specific patient data.\n\n"
    "Cover: medication review, lab interpretation, treatment efficacy, symptom follow-up, "
    "overdue follow-ups, preventive care, new concerns.\n"
    "{specialty_focus}"
    "RULES:\n"
    "- Every point must reference specific data (drug names, lab values with units/dates, conditions).\n"
    "- MEDICATION-INDICATION ACCURACY: MetXL/Metoprolol = beta-blocker for HYPERTENSION (NOT for diabetes). "
    "Amlodipine = calcium channel blocker for HYPERTENSION. If unsure about a drug's indication, "
    "say 'indication: review with doctor'. Never fabricate.\n"
    "- Most urgent points first. No filler. Address each diagnosed condition.\n"
)
